version:  "3"

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=Stinhdaica123"
    ports:
      - "1433:1433"
    hostname: mssql
    volumes:
      - "./db_data:/var/opt/mssql"